name: Documentation (preview)
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  documentation:
    name: Deploy preview documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          # Install a specific version of uv.
          version: "0.5.1"
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Install Documentation dependencies
        run: uv sync --group doc
      - name: Set up build cache
        uses: actions/cache@v6
        id: cache
        with:
          key: mkdocs-material-${{ github.ref }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - name: Depoly documentation
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          uv run mkdocs build
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./site
